name: Build web tests release

on:
  push:
    paths:
    - '.github/workflows/web_tests.yml'
    - 'scripts/prepare-web-tests.py'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_web_tests:
    name: Build Web Tests
    runs-on: ubuntu-20.04
    
    steps:
    - run: sudo apt-get update
    - run: sudo apt-get install -y python3 git subversion
    - run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - run: echo "$PWD/depot_tools" >> $GITHUB_PATH
    - run: rm -Rf /tmp/web_tests && mkdir /tmp/web_tests
    - run: python scripts/prepare-web-tests.py
      env:
        TESTS_ARCHIVE_NAME: web_tests.zip
        TESTS_DIR: /tmp/web_tests
    - uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Nightly Release
        draft: false
        prerelease: false
